# Sub-grammar for propositional LTL

<atom>     := <x-equals> | <v-equals>;
<x-equals> := <xpathfct> = <constant> ;
<xpathfct> := ^[\w\d/\(\)]+;
<constant> := ^[\w\d]+;

# Quantifiers

<dom-fct>  := <xpathfct>;
<v-equals> := <c-var> = <constant> ;
<var>      := ^\$[\w\d]+;
<c-var>    := ^\$[\w\d]+;