# ------------------------------------------------------------------
# Sub-grammar for propositional QEA
# (C) 2018 Sylvain Hallé
# ------------------------------------------------------------------

<fct>     := <atom> ;
<atom>    := ^[\w\d]+;
<dom-fct> := . ;